name: Deploy To Each Bucket

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Push Website
      run: |
        aws s3 cp --acl public-read --recursive --exclude "*" --include "*.html" . s3://iframe-referrer-bug.wizebin.com/
        aws s3 cp --acl public-read --recursive --exclude "*" --include "*.html" . s3://iframe-referrer-bug-2.wizebin.com/
        aws s3 cp --acl public-read --recursive --exclude "*" --include "*.html" . s3://iframe-referrer-bug.fullhermit.com/
        aws s3 cp --acl public-read --recursive --exclude "*" --include "*.html" . s3://iframe-referrer-bug.ultii.com/
